# Generated by Django 5.2.3 on 2025-10-09 08:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pastpaper', '0002_alter_pastpapercomponent_num_display'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('BUNDLING', 'Bundling'), ('READY', 'Ready for embedding'), ('EMBEDDING', 'Embedding'), ('EMBEDDED', 'Embedded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('bundle_count', models.PositiveIntegerField(default=0)),
                ('chunk_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundled_at', models.DateTimeField(blank=True, null=True)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunk_plans', to='pastpaper.pastpaper')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bundle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, default='', max_length=256)),
                ('component_ids', models.JSONField(blank=True, default=list)),
                ('span_paths', models.JSONField(blank=True, default=list)),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('root_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundle_roots', to='pastpaper.pastpapercomponent')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bundles', to='indexing.chunkplan')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='IndexProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=64, unique=True)),
                ('display_name', models.CharField(max_length=128)),
                ('description', models.TextField(blank=True, default='')),
                ('encoder', models.CharField(max_length=128)),
                ('tokenizer', models.CharField(max_length=128)),
                ('dimension', models.PositiveIntegerField()),
                ('max_input_tokens', models.PositiveIntegerField()),
                ('chunk_size', models.PositiveIntegerField()),
                ('chunk_overlap', models.PositiveIntegerField(default=0)),
                ('target_bundle_tokens', models.PositiveIntegerField(default=600)),
                ('qdrant_collection', models.CharField(max_length=128)),
                ('qdrant_distance', models.CharField(default='Cosine', max_length=32)),
                ('hnsw_m', models.PositiveIntegerField(default=32)),
                ('hnsw_ef_construct', models.PositiveIntegerField(default=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['is_active'], name='idx_profile_active'), models.Index(fields=['qdrant_collection'], name='idx_profile_collection')],
            },
        ),
        migrations.AddField(
            model_name='chunkplan',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='indexing.indexprofile'),
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('token_count', models.PositiveIntegerField(default=0)),
                ('char_start', models.PositiveIntegerField(default=0)),
                ('char_end', models.PositiveIntegerField(default=0)),
                ('embedding_status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('EMBEDDING', 'Embedding'), ('EMBEDDED', 'Embedded'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=16)),
                ('qdrant_point_id', models.CharField(blank=True, default='', max_length=128)),
                ('embedded_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bundle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='indexing.bundle')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='indexing.chunkplan')),
            ],
            options={
                'ordering': ['sequence'],
                'indexes': [models.Index(fields=['plan', 'sequence'], name='idx_chunk_plan_seq'), models.Index(fields=['embedding_status'], name='idx_chunk_status')],
                'unique_together': {('plan', 'sequence')},
            },
        ),
        migrations.AddIndex(
            model_name='bundle',
            index=models.Index(fields=['plan', 'sequence'], name='idx_bundle_plan_seq'),
        ),
        migrations.AlterUniqueTogether(
            name='bundle',
            unique_together={('plan', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='chunkplan',
            index=models.Index(fields=['paper', 'profile'], name='idx_plan_paper_profile'),
        ),
        migrations.AddIndex(
            model_name='chunkplan',
            index=models.Index(fields=['is_active'], name='idx_plan_active'),
        ),
    ]
