# Generated by Django 5.2.3 on 2025-09-28 03:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(db_index=True, max_length=255)),
                ('args', models.JSONField(default=list)),
                ('kwargs', models.JSONField(default=dict)),
                ('dedupe_key', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('running', 'running'), ('done', 'done'), ('error', 'error')], db_index=True, default='pending', max_length=16)),
                ('queued_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('picked_at', models.DateTimeField(blank=True, null=True)),
                ('visible_until', models.DateTimeField(blank=True, null=True)),
                ('picked_by', models.CharField(blank=True, db_index=True, default='', max_length=128)),
                ('scheduled_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('attempts', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('last_error', models.TextField(blank=True, default='')),
                ('result', models.JSONField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'scheduled_at'], name='service_ioj_status_28b782_idx'), models.Index(fields=['task_name', 'status'], name='service_ioj_task_na_c252ef_idx')],
            },
        ),
    ]
