# Generated by Django 5.2.3 on 2025-10-25 07:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                (
                    "monthly_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="USD price charged monthly.",
                        max_digits=9,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "monthly_credits",
                    models.PositiveIntegerField(
                        help_text="Credits granted each billing cycle."
                    ),
                ),
                ("concurrency_limit", models.PositiveSmallIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="New accounts start on the default plan.",
                    ),
                ),
                ("features", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["monthly_price"],
            },
        ),
        migrations.AddField(
            model_name="useraccountmeta",
            name="current_cycle_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccountmeta",
            name="next_billing_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="useraccountmeta",
            name="plan_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="BillingCycle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("current", "Current"), ("closed", "Closed")],
                        default="current",
                        max_length=20,
                    ),
                ),
                ("cycle_start", models.DateTimeField()),
                ("cycle_end", models.DateTimeField()),
                ("monthly_allocation", models.PositiveIntegerField()),
                ("rollover_allocation", models.PositiveIntegerField(default=0)),
                (
                    "bonus_allocation",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Credits added via proration or adjustments.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_cycles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_cycles",
                        to="accounts.plantier",
                    ),
                ),
            ],
            options={
                "ordering": ["-cycle_start"],
            },
        ),
        migrations.CreateModel(
            name="CreditUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("credits_used", models.PositiveIntegerField()),
                ("reason", models.CharField(max_length=120)),
                ("source_summary", models.JSONField(blank=True, default=list)),
                ("reference_type", models.CharField(blank=True, max_length=80)),
                ("reference_id", models.CharField(blank=True, max_length=120)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="usage_logs",
                        to="accounts.billingcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="useraccountmeta",
            name="pending_plan",
            field=models.ForeignKey(
                blank=True,
                help_text="Plan that will activate on the next billing renewal.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="pending_account_metas",
                to="accounts.plantier",
            ),
        ),
        migrations.AddField(
            model_name="useraccountmeta",
            name="plan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="account_metas",
                to="accounts.plantier",
            ),
        ),
        migrations.CreateModel(
            name="CreditLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly allocation"),
                            ("rollover", "Rollover"),
                            ("promo", "Promotional"),
                            ("top_up", "Top up"),
                            ("adjustment", "Adjustment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_identifier", models.CharField(blank=True, max_length=120)),
                ("amount", models.PositiveIntegerField()),
                ("remaining_amount", models.PositiveIntegerField()),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ledger_entries",
                        to="accounts.billingcycle",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_ledger",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "remaining_amount"],
                        name="idx_ledger_user_remaining",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="billingcycle",
            constraint=models.UniqueConstraint(
                fields=("user", "cycle_start"), name="unique_cycle_per_user_and_start"
            ),
        ),
    ]
