# Generated by Django 5.2.3 on 2025-09-24 09:42

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PastPaperAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='pastpapers/%Y/%m/%d/')),
                ('mime', models.CharField(blank=True, default='application/pdf', max_length=64)),
                ('size', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(max_length=64)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('url_source', models.CharField(blank=True, max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'indexes': [models.Index(fields=['checksum_sha256'], name='pastpaper_p_checksu_d466d2_idx')],
            },
        ),
        migrations.CreateModel(
            name='PastPaperMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_code', models.CharField(max_length=255, unique=True)),
                ('exam_board', models.CharField(max_length=64)),
                ('subject', models.CharField(max_length=128)),
                ('syllabus_code', models.CharField(blank=True, default='', max_length=64)),
                ('season', models.CharField(blank=True, default='', max_length=64)),
                ('year', models.IntegerField()),
                ('variant_no', models.CharField(blank=True, default='', max_length=16)),
                ('paper_type', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['exam_board', 'subject', 'syllabus_code'], name='pastpaper_p_exam_bo_8128de_idx'), models.Index(fields=['year', 'paper_type', 'variant_no'], name='pastpaper_p_year_9d75c6_idx'), models.Index(fields=['paper_code'], name='pastpaper_p_paper_c_f4e412_idx')],
            },
        ),
        migrations.CreateModel(
            name='PastPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('version_no', models.PositiveIntegerField(editable=False)),
                ('parsed_state', models.CharField(choices=[('PENDING', 'PENDING'), ('RUNNING', 'RUNNING'), ('READY', 'READY'), ('ERROR', 'ERROR')], default='PENDING', max_length=16)),
                ('last_error', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parsed_tree', models.JSONField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='past_papers', to='pastpaper.pastpaperasset')),
                ('metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='past_papers', to='pastpaper.pastpapermetadata')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PastPaperComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_display', models.CharField(max_length=16)),
                ('path_normalized', models.CharField(blank=True, default='', max_length=128)),
                ('depth', models.IntegerField(default=0)),
                ('content', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
                ('position', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='pastpaper.pastpaper')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pastpaper.pastpapercomponent')),
            ],
            options={
                'indexes': [models.Index(fields=['paper', 'num_display'], name='pastpaper_p_paper_i_d4164a_idx'), models.Index(fields=['path_normalized'], name='pastpaper_p_path_no_25c0fa_idx'), models.Index(fields=['depth'], name='pastpaper_p_depth_b3d796_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['paper_id'], name='pastpaper_p_paper_i_daf864_idx'),
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['metadata'], name='pastpaper_p_metadat_ae064b_idx'),
        ),
        migrations.AddIndex(
            model_name='pastpaper',
            index=models.Index(fields=['is_active'], name='pastpaper_p_is_acti_d3f2b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='pastpaper',
            unique_together={('paper_id', 'version_no')},
        ),
    ]
