# Generated by Django 5.2.3 on 2025-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastpapercomponent',
            name='num_display',
            field=models.CharField(max_length=64),
        ),
    ]
