# Generated by Django 5.2.3 on 2025-10-10 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pastpaper', '0003_trigram_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pastpapercomponent',
            name='component_content_trgm',
        ),
        migrations.RemoveIndex(
            model_name='pastpapercomponent',
            name='component_num_trgm',
        ),
        migrations.RemoveIndex(
            model_name='pastpapercomponent',
            name='component_path_trgm',
        ),
    ]
